### ISSUE TITLE
The website http://www.semantic-paint.com is a pornographic website.

### ISSUE THREAD

**Issue by MyEvolution** [torrvision/spaint#14]
The website http://www.semantic-paint.com is a pornographic website.

**Comment by sgolodetz** [comment]
Hmm, disturbing. I guess Oxford stopped paying for the domain name :(

**Comment by sgolodetz** [comment]
So it doesn't immediately look like a pornographic website - but it's definitely not pointing to our work any more. I'll check with the university.

**Comment by sgolodetz** [comment]
I've updated the link to the project page in the meantime.

**Comment by MyEvolution** [comment]
In fact, it's a Chinese pornographic website.  Maybe you need to change the domain as soon as possible. And I can change the issue😁 张国庆 邮箱：wlsdzyzl@gmail.com 签名由 网易邮箱大师 定制 On 10/24/2019 20:11, Stuart Golodetz wrote: So it doesn't immediately look like a pornographic website - but it's definitely not pointing to our work any more. I'll check with the university. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by sgolodetz** [comment]
Not sure I can do much about the domain - I guess someone else owns it now. We can update the links on our pages though.

**Comment by sgolodetz** [comment]
Thanks for pointing it out anyway! What a mess.
