### ISSUE TITLE
How do you get the optimized pose?

### ISSUE THREAD

**Issue by Tom-Zheng** [torrvision/spaint#15]
I noticed that both the `reconstruct-global.sh` and `reconstruct-collaborative.sh` read the pose for every frame from disk, by specifying the `-t Disk` argument. But how can I get these poses, e.g., for a new sequence? When I try to remove the `-t Disk` argument and instead use `-t InfiniTAM` tracker, the tracking was immediately lost after a few frames. I also have confusions on how do I get the `global_poses.txt` for a new dataset. Any advice on how I can reproduce the results or start from a new sequence?

**Comment by lululovecode** [comment]
Hello,I met the same problems as you.Have you solved those problems?Thx!
