### ISSUE TITLE
Old semantic paint website link should be removed

### ISSUE THREAD

**Issue by eguendelman** [torrvision/spaint#16]
Hi,
The About section of this project links to a project webpage (semantic paint dot com) which is no longer relevant and, um, quite NSFW 😕 ...  
Probably better to remove/update...

Thanks 😄

**Comment by eguendelman** [comment]
@sgolodetz

**Comment by sgolodetz** [comment]
@eguendelman Oops, I thought I'd fixed all the links to that - thanks for pointing it out!
