### ISSUE TITLE
Physical touch detection failed

### ISSUE THREAD

**Issue by chinapipa** [torrvision/spaint#2]
Hello, I want to use your touching interaction to label and segment object, but there is strange content in the render window when I run the program.
Like the picture below. (And it changed every time I run the program.)
![semanticpaint_strange](https://user-images.githubusercontent.com/20423057/29020890-243f5d3a-7b96-11e7-8bb2-ed9b93f47c69.png)

I build InfiniTAM and spaint successfully. 
Here are my environment and device:
>Operating System: Ubuntu 14.04 (64-bit)
>Memory: 15.6GiB
>Processor: Intel Core i7-6700 CPU@3.40GHz*8
>Graphics: GeForce GTX 1060 6GB/PCIe/SSE2
>(NVidia driver version is 375.66)
>Device: ASUS Xtion Pro Live

Here are my 3rd party libraries and version:
>ArrayFire: 3.6.0
>Boost: 1.56
>CUDA: 8.0
>Eigen: 3.2.2
>GLEW: 1.12.0
>InfiniTAM: version 2 (use branch spaint_v2)
>OpenCV: 2.4.9
>OpenGL
>OpenMP
>OpenNI: version 2
>SDL: version 2-2.0.3

CMake Configuration enable these Flag:
>WITH_ARRAYFIRE
>WITH_CUDA
>WITH_OPENCV
>WITH_OPENMP
>WITH_OPENNI

If I disable WITH_ARRAYFIRE, the live reconstruction and picking mode can run normally.

My questions are:
1. Is any library I need to install for touch interaction?
2. Below are failed tests when I run the test program in arrayfire:
>solve_dense_cpu
>cholesky_dense_opencl
>fftconvolve_opencl
>qr_dense_opencl
>solve_dense_opencl

Would those fails influence the touch interaction?

3. I check the code, see this block: 
>if(af::getDeviceCount() > 1)
>{
>    af::setDevice(1);
>}

Does the touch interaction need more than one depth camera?(one for reconstruction and one for user hand?)

4. Or, any other suggestion to solve this problem?

Thanks a lot!

**Comment by sgolodetz** [comment]
Hmm, interesting! Regarding (3), that code checks for multiple GPUs, and uses the second one if there's more than one (it was added because we were having trouble using ArrayFire on a multi-GPU system if it was running on the primary GPU). Regarding (2), I don't think those test failures are related, but I'm not sure. I'll need to think a bit more about how to solve the problem itself - not sure at the moment.

**Comment by chinapipa** [comment]
Thank you for quick reply!

So I can ignore (3)'s code block if I have only one GPU?

Besides, I build arrayfire from source code and the OpenCL SDK version which I used is Nvidia CUDA.
And when build spaint system I see it need clblas and clfft libraries. (I build them from source code, too.)
Those libraries seem that they are optimized for the AMD GPU hardware.
Should I change to AMD GPU or change to use CUDA libraries like cublas and cufft?

Thanks again.

**Comment by chinapipa** [comment]
Hello, the system works fine(i.e. the live reconstruction and picking mode can run successfully.) after stuck in the strange content for about 1 minute.
(But I don't know why.)

However, It will crash when I change to touch selector(press keyboard I+4).
The error message is as follows:
>ArrayFire Exception (Device out of memory:101):
>In function void* cuda::MemoryManager::nativeAlloc(size_t)
>In file src/backend/cuda/memory.cpp:178
>CUDA Error (2): out of memory
>
>
>In function void af::initEmptyArray(void**, af::dtype, dim_t, dim_t, dim_t, dim_t)
>In file src/api/cpp/array.cpp:111

Is there any other setting I missed? Thanks.

**Comment by chinapipa** [comment]
Hi, I found that it would get this error message: (In addition to CUDA's out of memory error)
`SemanticPaint/spaint/../InfiniTAM/InfiniTAM/ITMLib/Objects/../Utils/../Objects/../../ORUtils/MemoryBlock.h(141) : cudaSafeCall() Runtime API error : an illegal memory access was encountered.`

I think that maybe the touch selector can only run on multiple GPUs environment because of the memory access. Both the main reconstruction and the arrayfire want to use the GPU.

I don't have another GPU to check if it is correct. It just a guess by myself.

**Comment by sgolodetz** [comment]
@chinapipa: It can definitely run on one GPU - I run it on a GeForce 980M on my laptop. Looks like there's a bug somewhere though - maybe try turning on ORcudaKernelCheck and then debugging to see where it crashes.

**Comment by chinapipa** [comment]
Thank you! I will try it.

**Comment by chinapipa** [comment]
Hi, I finally solved the problem!
After tracing the code, I found your comment in MedianFilterer.cpp:

>  // FIXME: Median filtering can occasionally fail due to a possible crash bug in ArrayFire. If this happens,
>  //        we currently avoid throwing and instead treat this function as a no-op.

I skip this function and the system run successfully with touching interaction although the quality is not as good as your demo video.

Does the function just use the median filter to denoise the data? If so, maybe I can try other method(not use ArrayFire) to reimplement it?

**Comment by sgolodetz** [comment]
@chinapipa: It denoises the rendered image to make it look a little nicer (see `Renderer::render_reconstructed_scene`). There's also a label smoother implemented that works on the actual voxel data (see the `smoothing` subdirectory in `spaint`) - that does something a little like median filtering, but using our own code, and only runs when you're in the relevant pipeline mode.

**Comment by chinapipa** [comment]
Thanks a lot!
