### ISSUE TITLE
Will the whole scene be labeled in test mode?

### ISSUE THREAD

**Issue by billamiable** [torrvision/spaint#5]
Hi, 

I got a little confused about the difference between your uploaded video and my implementation case.

> In supplementary video, i found that the background will not be labeled as follows:
![gt](https://user-images.githubusercontent.com/16483494/34338377-2918d1a8-e9a3-11e7-8756-54ef9ad6dee0.png)

However, when i test in my office scene, the whole scene will be labeled. I'm really curious about the reason.

Is there anything i've missed? Thanks!

**Comment by sgolodetz** [comment]
There are two different versions - the video is from the original version implemented by Julien, Vibhav and Ming-Ming, the open-source code was implemented by me and Mike. They don't work in exactly the same way, hence the observed differences.

**Comment by billamiable** [comment]
Got it, thanks!
