### ISSUE TITLE
what is the meaning of voxel coordinates? 

### ISSUE THREAD

**Issue by 627633854** [torrvision/spaint#6]
//Convert the pick point from voxel coordinates into scene coordinates and return it.
I am confused ,and what's the relationship between voxel coordinates and  scene coordinates?i can't find it in the framework.

I also can't find the value of voxelSize  (The size of an InfiniTAM voxel (in metres)).

**Comment by sgolodetz** [comment]
Voxel coordinates refer to specific voxels in the voxel grid - e.g. (2,3,1) would be the third voxel along in x, the fourth in y and the second in z. Voxels are cubes of a certain size - to work out where a particular point in voxel coordinates really is in the scene, you thus have to multiply through by the voxel size. The voxel size itself is in ITMLibSettings in InfiniTAM. You can change it in the main function of spaintgui if need be.

**Comment by 627633854** [comment]
Thank you.
