### ISSUE TITLE
problems when running the spaintgui.exe

### ISSUE THREAD

**Issue by cy19971107** [torrvision/spaint#9]
I think I build the spaint successfully, but when I run the  spaintgui.exe I get the result as following:

[spaint] Found 0 joysticks.
Cannot get the RGB image size from an empty composite image source engine

What's the reason of getting this result?
and when I run this with openNI and want to open the picture in InfiniTAM:
./spaintgui Teddy/calib.txt Teddy/Frames/%04i.ppm Teddy/Frames/%04i.pgm
I get:
[spaint] Found 0 joysticks.
[spaint] Probing OpenNI camera: Default
Calibration filename not specified. Using default parameters.
compiled without OpenNI support
Cannot get the RGB image size from an empty composite image source engine

Why I cannot open the file with spaint?

Thank you

**Comment by sgolodetz** [comment]
It looks like you've built without OpenNI support - if you rebuild with that enabled (for both InfiniTAM and spaint) and plug in a supported camera then it should work.

Regarding the one with the sequence, I think I need to update the README - the way in which you specify sequences on the command line got upgraded, but the README wasn't updated accordingly. The way it works now is that you can either make a 'sequences' subdirectory below the directory containing the executable, put Teddy in that and then specify '-s Teddy' on the command line, or you can put it elsewhere and specify '-s full-path'. There's also still a way to specify the calibration file, depth mask and RGB mask separately via '-c', '-d' and '-r'. See also main.cpp.

**Comment by cy19971107** [comment]
I run the spaintgui.exe successfully and open the file. But I have  another question:
"plug in a supported camera"
what kind of camera is supported? only Kinect?
thank you.

**Comment by cy19971107** [comment]
Only have Intel Creative Senz3D to use……Is it supported?
And if I want to use additional libraries/drivers ( for example, Creative Senz3D camera would work with Intel Perceptual Computing (PerC) SDK  ,I have installed it),how can I connect it to the spaint project?

**Comment by sgolodetz** [comment]
You'll probably need to write your own ImageSourceEngine - see the InputSource project in InfiniTAM.

**Comment by sgolodetz** [comment]
Either in principle, in the sense that I think @victorprad had a Kinect 2 image source engine implemented in InfiniTAM. I've only used the Kinect 1 one though, as I don't personally have a Kinect 2. From what I remember, the Kinect 2 didn't work so well - so not sure what the current state of the image source engine is for that. Probably wouldn't be too hard to get it up and running though.

**Comment by cy19971107** [comment]
I have connected the camera and get picture I want successfully, but now I have some trouble interacting with scene.It seems that I need to choose
WITH_ARRAYFIRE
WITH_CUDA
WITH_OPENMP
WITH_OPENNI
Is WITH_CUDA must be choosen for interacting with scene ?

**Comment by sgolodetz** [comment]
You need ArrayFire for touch interaction. Can't remember if it can work without CUDA - wouldn't recommend it if you can avoid it, will be slow.

**Comment by cy19971107** [comment]
I install cuda and arrayfire and choose with cuda + with arrayfire in cmake to compile the spaint, but there is a problem:
in the file "ImageProcessor.h" use #include <arrayfire.h> ,when I run the spaint , "cannot open the arrayfire.h",it seems that the program is not connected to arrayfire.
And I see the cmake, I find that there is no entry for arrayfire like ArrayFire_INCLUDE_DIR orArrayFire_LIBRARY OR ArrayFire_ROOT ,is this the reason why I cannot connect ArrayFire to spaint?How can I coonect ArrayFire to spaint?
Thank you.

**Comment by cy19971107** [comment]
Also , what the default compiler of spanit program? 32 bits or 64 bits?
I run spaint successfully only  on 32 bits , but the arrayfire on windows only have 64 bits version……

**Comment by cy19971107** [comment]
1.png
@sgolodetz
I have downloaded the new resource of spaint from github.
I think there may be some errors about the scratchtest_cuda build……
I have tried many ways to deal with this problem，but it doesn't work.
erros:
scratchtest_cuda_intermediate_link.obj : error LNK2019: unresolved external symbol __fatbinwrap_30_ztrmm_sm35_cpp2asm_asm_cpp1_ii_2af62f32 referenced in function
spaint\build\bin\tests\scratch\scratchtest_cuda\scratchtest_cuda.exe : fatal error LNK1120: 183 unresolved externals

**Comment by cy19971107** [comment]
There are some errors in scratchtest_cuda build,but I don't know how to deal with it.
scratchtest_cuda_intermediate_link.obj : error LNK2019: unresolved external symbol __fatbinwrap_30_ztrmm_sm35_cpp2asm_asm_cpp1_ii_2af62f32 referenced in function __cudaRegisterLinkedBinary_30_ztrmm_sm35_cpp2asm_asm_cpp1_ii_2af62f32
……
scratchtest_cuda_intermediate_link.obj : error LNK2019: unresolved external symbol __fatbinwrap_38_cuda_device_runtime_compute_70_cpp1_ii_8b1a5d37 referenced in function __cudaRegisterLinkedBinary_38_cuda_device_runtime_compute_70_cpp1_ii_8b1a5d37
scratchtest_cuda.exe : fatal error LNK1120: 183 unresolved externals

**Comment by cy19971107** [comment]
sorry to bother you but I find an important bug when buiding the spaintgui.
I search the internet,and I  guess the reason is code error but I don't know how to deal with it.
the bug is :
spaint_d.lib(spaint_intermediate_link.obj) : error LNK2005: __cudaRegisterLinkedBinary_30_ztrmm_sm35_cpp2asm_asm_cpp1_ii_2af62f32 already defined in spaintgui_intermediate_link.obj
……
itmx_d.lib(itmx_intermediate_link.obj) : error LNK2005: __cudaRegisterLinkedBinary_30_ztrmm_sm35_cpp2asm_asm_cpp1_ii_2af62f32 already defined in spaintgui_intermediate_link.obj
……
fatal error LNK1169: one or more multiply defined symbols found

**Comment by sgolodetz** [comment]
@cy19971107: Try rerunning the build script from Git Bash - I find I get these errors sometimes also, I think they're caused by stale files. Rerunning the build script seems to fix it.

**Comment by sgolodetz** [comment]
Hmm, CUDADefines.h doesn't define any variables obviously. Why do you think it's that? Can you email me your CMakeCache.txt file from the build directory? Might help me have a think about what's going on.

**Comment by sgolodetz** [comment]
This might be relevant:

https://gitlab.kitware.com/cmake/cmake/issues/17520

**Comment by cy19971107** [comment]
[CMakeCache.txt](https://github.com/torrvision/spaint/files/2064596/CMakeCache.txt)

Here is my CMakeCache.txt

**Comment by sgolodetz** [comment]
So one thing that occurred to me was that it might be a CMake version issue - they added first-class support for CUDA recently, and I found on Mac that my build broke when I tried to use CMake 3.11 rather than 3.9. You could try an older version of CMake to see if that fixes it - it might just be that I need to upgrade the build to work with new CMake. I'm building with 3.9 or older on all platforms, and it works happily enough on a variety of different machines, so that's a likely suspect for why it might not be working for you.

**Comment by sgolodetz** [comment]
One other thing that looks weird in your CMakeCache.txt is the location of InfiniTAM. Are you building against the infinitam_v3.5 branch? The master branch of spaint is set up to build against that, by default looking in a sibling directory of spaint called infinitam (lower case).

**Comment by sgolodetz** [comment]
You may have older versions of both InfiniTAM and spaint fetched also - if so, might be a good idea to update as the folder structure changed in InfiniTAM from 3 -> 3.5 (we changed InfiniTAM/InfiniTAM to infinitam).

**Comment by cy19971107** [comment]
build errors with Boost 1.56.0：
![18 06 02 1250_1](https://user-images.githubusercontent.com/34977127/40870513-c78b39e2-6663-11e8-98d4-e8012f94f1a8.png)
error C2664: 'void std::_Tree<std::_Tmap_traits<_Kty,_Ty,_Pr,_Alloc,false>>::insert(std::initializer_list<std::pair<const _Kty,_Ty>>)' : cannot convert argument 1 from 'std::pair<const void *,boost::shared_ptr<const rafl::Example<Label>>>' to 'std::pair<const _Kty,_Ty> &&'……

**Comment by sgolodetz** [comment]
Did you build Boost with the build script?

https://github.com/torrvision/spaint/blob/master/libraries/build-boost_1_56_0-win.sh

There's a fix for shared_ptr_helper.hpp embedded in that. If you built manually, you might not have picked it up.

**Comment by cy19971107** [comment]
Now I build the spaint successfully! I  think boost 1.67.0 is still ok for this project.
I think the bug I had yesterday is caused by **cmake 3.11.0**, now I use **cmake  3.9** so the bug does not occur.
But it seems that I need **afcuda.dll** for running the spaintgui.exe , where can I find this file?

**Comment by sgolodetz** [comment]
Yes, Boost 1.67.0 should work too - don't think there are any serious interface changes that will affect it. I should update the readme to say CMake 3.9 for now - apparently 3.11 needs some changes to work. The missing DLL is in the ArrayFire bin directory IIRC - the build should copy it across by default, but you can always do it manually if not.

**Comment by sgolodetz** [comment]
Hmm maybe it doesn't at the moment for some reason:

https://github.com/torrvision/spaint/blob/master/cmake/LinkArrayFire.cmake

You might also need the nvvm DLL for CUDA 9. I've been using an earlier CUDA version, so the LinkArrayFire.cmake script may need updating slightly for CUDA 9.

**Comment by cy19971107** [comment]
OK I copy the dll file which ArrayFire needs by my hand, and the spaintgui.exe can run successfully.
I still have some problems.
1.Do grove need to be built if I want to  interacting with scene ?
2.My build options are here, What else do I need to choose?
![18 06 02 1501_2](https://user-images.githubusercontent.com/34977127/40871835-0b6b50f4-6676-11e8-9939-39c41cafb03b.png)
![18 06 02 1501_1](https://user-images.githubusercontent.com/34977127/40871836-0f2d4148-6676-11e8-82bf-75b4bba5941d.png)

 3.I want to try how to color the image I get in the spaint,I enter I +4 to spaint ,but I don't know what to do next.
4.The spaint is running too slowly,how can I make it quicker?

**Comment by cy19971107** [comment]
I build both InfiniTAM and SemanticPaint in Release mode.
I enter the I+4 and touch the scene in the real world ，but nothing happened.
Also, After I enter I+4 to the program,after a shourt time the spaintgui.exe will close by itself automatically although I don't want it to close.

**Comment by cy19971107** [comment]
I press I+2  and there is a orange point on my mouse , what should I do to  label the scene?

**Comment by sgolodetz** [comment]
Click the scene. Also, press H for the shortcut keys to change label / labelling size.

**Comment by sgolodetz** [comment]
For the voice, you need to use a separate Java application called voicecommander - I'm about to drive home, so I'll have to help with that later. The GPU on your machine looks a bit underpowered I think, which might explain some of the problems you're having:

https://www.notebookcheck.net/NVIDIA-GeForce-940MX.156033.0.html

Will have to try to debug what's going on later.

Bear in mind that it won't look exactly like Ming's video, since there are two different implementations and that's from the other one, but if we get it working it will be close.

**Comment by cy19971107** [comment]
Ok, I hope you can help me with these problems when you have time.
1.So I need to install the voicecommander?where can I get this application,how I can connect it to spaint?
2.“The GPU on your machine looks a bit underpowered” But this is not the thing I can control……Can I finish the project on this GPU?

**Comment by sgolodetz** [comment]
1. You can clone it from here: git@bitbucket.org:sgolodetz/voicecommander.git

When you run it, it runs a local voice command server to which spaintgui will connect (start voicecommander first).

2. Not sure, will need some debugging (and possibly decreasing the number of locally stored blocks in `ITMVoxelBlockHash.h`, if it's a memory issue). As a starting point, not sure if you saw my question above - if you run spaintgui from the command line and press I+4, do you get any error message in the terminal (e.g. an exception message)?

**Comment by sgolodetz** [comment]
Re. GPU performance btw - for reference, I have a GeForce 560M on my Macbook, and this is how your GPU stacks up against it:

http://www.game-debate.com/gpu/index.php?gid=504&gid2=3455&compare=Nvidia%20GeForce%20GTX%20560M-vs-Nvidia%20GeForce%20940MX%202GB

SemanticPaint really grinds on my Macbook (vs. the sort of laptop we use for a conference demo, which has a 980M in it):

http://www.game-debate.com/gpu/index.php?gid=3455&gid2=2443&compare=Nvidia%20GeForce%20940MX%202GB-vs-Nvidia%20GeForce%20GTX%20980M%208GB

So I think what I'm trying to say is - no promises on how well it will work on your GPU unfortunately. It hasn't been optimised for that kind of GPU, and with only 2GB of memory, you're quite likely to hit problems. I had to manually decrease the memory usage to get things to run ok on my Macbook. You could try turning on `USE_LOW_POWER_MODE` in CMake - that turns off colour information in the voxels, which will save some memory.

**Comment by cy19971107** [comment]
I didn't get any bug  from the command line when I enter I +4 to spaint, it just close automatically.
BUt there is a bug when I run the RUN_TEST in vs2013:
![18 06 03 2230_2](https://user-images.githubusercontent.com/34977127/40887591-c22f3870-677d-11e8-8bd7-1352983b4484.png)

now I  try to build the voicecommander,but I get this bug BUT I don't know why.
![18 06 03 2228_1](https://user-images.githubusercontent.com/34977127/40887577-7dc87476-677d-11e8-9330-7b2264dc8593.png)

**Comment by sgolodetz** [comment]
So you should be able to do `ant run` to run it, and then `spaintgui` should be able to connect to it. If you plug in a microphone, then say different commands into it, their effects should happen in `spaintgui`. See in particular `Application::process_voice_input()` for the commands you can use.

Regarding the test failure - try putting a breakpoint at the start of `copy_image_test` and stepping through to see where it fails. The two problems are very likely related, since it's probably something to do with the use of ArrayFire. If it doesn't get as far as `copy_image_test`, try putting a breakpoint in the `CopyImageFixture` constructor instead.

**Comment by cy19971107** [comment]
I open it and connect it to spanit . BUT how can I close the  voicecommander ?

**Comment by sgolodetz** [comment]
Ctrl + C? There's no "quit" voice command as things stand - but see `Application::process_voice_input()` if you want to add one.

**Comment by cy19971107** [comment]
I enter Ctrl + C but the voicecommander did not close, I have to close the git bash to make it close.
Now  I run the RUN_TEST and all the tests pass. I think the bug before is caused by some dll files loss.I add them so all the tests pass.
![18 06 04 0058_3](https://user-images.githubusercontent.com/34977127/40889024-64fc28d8-6792-11e8-994e-e080c0a09b30.png)
![18 06 04 0053_2](https://user-images.githubusercontent.com/34977127/40889028-6c109cda-6792-11e8-99b2-45647048e41e.png)
But my spaint still can not run well.
![18 06 04 0019_1](https://user-images.githubusercontent.com/34977127/40889042-8b1c32a6-6792-11e8-8c79-84550247e787.png)

**Comment by cy19971107** [comment]
@sgolodetz  
Oh my god I find an amzing thing.
I try not to build InfiniTAM and spaint with CUDA. Then I enter I+4 to spaintgui.exe and I run the program successfully.
I think maybe CUDA is not so useful on my computer:) Thank you for all your help these days.

**Comment by sgolodetz** [comment]
No problem - glad it works ok in CPU mode at least!
